export enum PersonType {
  NATURAL = 'NATURAL',
  JURIDICA = 'JURIDICA',
}

export enum TaxRegime {
  RESPONSABLE_IVA = 'RESPONSABLE_IVA',
  NO_RESPONSABLE_IVA = 'NO_RESPONSABLE_IVA',
  REGIMEN_SIMPLE = 'REGIMEN_SIMPLE',
}

export enum CompanyType {
  COMMERCIAL = 'COMMERCIAL',
  SERVICES = 'SERVICES',
  MANUFACTURING = 'MANUFACTURING',
  MIXED = 'MIXED',
}
