export enum MasterlistCategory {
  BUSINESS_PROFILE = 'BUSINESS_PROFILE',
  TAX_TYPE = 'TAX_TYPE',
  TAX_TREATMENT = 'TAX_TREATMENT',
  DIAN_TAX_RESPONSIBILITY = 'DIAN_TAX_RESPONSIBILITY',
  DOCUMENT_TYPE = 'DOCUMENT_TYPE',
  THIRD_PARTY_ROLE = 'THIRD_PARTY_ROLE',
  CURRENCY = 'CURRENCY',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  COMPANY_TYPE = 'COMPANY_TYPE',
  INVENTORY_MOVEMENT_TYPE = 'INVENTORY_MOVEMENT_TYPE',
  COLOMBIA_DEPARTMENT = 'COLOMBIA_DEPARTMENT',
  COLOMBIA_CITY = 'COLOMBIA_CITY',
}
