export enum MasterlistCategory {
  BUSINESS_PROFILE = 'BUSINESS_PROFILE',
  TAX_TYPE = 'TAX_TYPE',
  TAX_TREATMENT = 'TAX_TREATMENT',
  DIAN_TAX_RESPONSIBILITY = 'DIAN_TAX_RESPONSIBILITY',
  DOCUMENT_TYPE = 'DOCUMENT_TYPE',
}
