import {inject} from '@loopback/core';
import {DefaultCrudRepository, AnyObject} from '@loopback/repository';
import {Product} from '../../../domain/inventory/entities/product.entity';
import {IProductRepository} from '../../../domain/inventory/repositories/product.repository.interface';
import {InventoryMapper} from '../mappers/inventory.mapper';
import {ProductModel} from '../models/product.model';
import {PostgresDataSource} from '../../database/datasources/postgres.datasource';

export class ProductRepository implements IProductRepository {
  private lbRepository: DefaultCrudRepository<
    ProductModel,
    typeof ProductModel.prototype.id
  >;

  constructor(@inject('datasources.postgres') dataSource: PostgresDataSource) {
    this.lbRepository = new DefaultCrudRepository(ProductModel, dataSource);
  }

  async save(product: Product, options?: AnyObject): Promise<Product>  {
    // La lógica de negocio detallada de este caso de uso o implementación de infraestructura
    // es privada y comercial. Se muestra únicamente la arquitectura y firma del método.
    throw new Error("Showcase: Método no implementado.");
  } else {
      // Create new (ID should be generated by Mapper if missing)
      savedModel = await this.lbRepository.create(model, options);
    }
    return InventoryMapper.toProductDomain(savedModel);
  }

  async findById(id: string, options?: AnyObject): Promise<Product | null>  {
    // La lógica de negocio detallada de este caso de uso o implementación de infraestructura
    // es privada y comercial. Se muestra únicamente la arquitectura y firma del método.
    throw new Error("Showcase: Método no implementado.");
  } catch (e)  {
    // La lógica de negocio detallada de este caso de uso o implementación de infraestructura
    // es privada y comercial. Se muestra únicamente la arquitectura y firma del método.
    throw new Error("Showcase: Método no implementado.");
  }
  }

  async findBySku(
    tenantId: string,
    sku: string,
    options?: AnyObject,
  ): Promise<Product | null>  {
    // La lógica de negocio detallada de este caso de uso o implementación de infraestructura
    // es privada y comercial. Se muestra únicamente la arquitectura y firma del método.
    throw new Error("Showcase: Método no implementado.");
  },
      },
      options,
    );
    return model ? InventoryMapper.toProductDomain(model) : null;
  }

  async findByCompanyId(
    companyId: string,
    options?: AnyObject,
  ): Promise<Product[]>  {
    // La lógica de negocio detallada de este caso de uso o implementación de infraestructura
    // es privada y comercial. Se muestra únicamente la arquitectura y firma del método.
    throw new Error("Showcase: Método no implementado.");
  }}, options);
    return models.map(InventoryMapper.toProductDomain);
  }
}
